### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by daniel2130** [uhppoted/uhppoted-mqtt#1]
Hi, I just found your project its really great i just dont find anywhere the info on where to config the mqtt connection to my broker is there any info that i could have not found.
Thanks in advance and have a good day !

**Comment by uhppoted** [comment]
Hi,

Thank you! It's always good to hear that somebody is finding it useful :-).

The configuration information is typically located in the communal _uhppoted.conf_ file, which by default is expected to be in one of the following location:
- `/etc/uhppoted/uhppoted.conf` (Linux)
- `/usr/local/etc/com.github.uhppoted/uhppoted.conf` (MacOS)
- `C:\ProgramData\uhppoted\uhppoted.conf` (Windows)

Alternatively you can specify a configuration file with the`--config` command line flag, e.g. `./uhppoted-mqtt run --config myconf.conf --console`.

A minimal MQTT `conf` contains the following information:
```
# SYSTEM
bind.address = 192.168.1.100:0
broadcast.address = 192.168.1.255:60000
listen.address = 192.168.1.100:60001

# MQTT
mqtt.connection.broker = tcp://localhost:1883
mqtt.connection.client.ID = me
mqtt.connection.username = it
mqtt.connection.password = them
mqtt.security.authentication = NONE
mqtt.security.outgoing.sign = false
mqtt.security.outgoing.encrypt = false
```

This configures `uhppoted-mqtt` to connect to the MQTT broker with a simple TCP/IP connection i.e. no TLS, authentication or encryption. To get a complete list of all the configuration options, use the `config` command:
```
./uhppoted-mqtt config
```

A quick way to get a basic working _uhppoted.conf_ file is to use the `config` command, pipe it to the configuration file and then remove all the unwanted information, e.g.:
```
./uhppoted-mqtt config > myconf.conf
```
Hope that gets you started! 

**NOTE 1**: _the message formats are not documented as yet because they are still subject to change - however the _Makefile_ has examples for every supported command_.

**NOTE 2**: _depending on your requirements, it may be worth taking a look at the [node-red-contrib-uhppoted](https://github.com/uhppoted/node-red-contrib-uhppoted) project. The [NodeRED](https://nodered.org) base library includes nodes to communicate with an MQTT broker so wiring up a UHPPOTED controller to an MQTT broker is relatively straightforward_.

**Comment by uhppoted** [comment]
Hi,

I've added a [working example](https://github.com/uhppoted/uhppoted/tree/master/docker/uhppoted-mqtt) for `uhppoted-mqtt` using Docker and it includes the [configuration](https://github.com/uhppoted/uhppoted/blob/master/docker/uhppoted-mqtt/uhppoted.conf) for a TLS connection to the MQTT broker.

Am going to close this - feel free to reopen if you have any further questions.
