### ISSUE TITLE
Is it possible to get the "User ID" from uhppoted/gateway/events/live ??

### ISSUE THREAD

**Issue by manu-benoit** [uhppoted/uhppoted-mqtt#18]
Hello, 

Everything seems to be running smoothly so far, but I was curious to know if I can get the "User ID" as a payload (not sure of the terminology) from the events.

Here is was I get from the uhppoted-mqtt:

{
  "message": {
    "event": {
      "event": {
        "access-granted": true,
        "card-number": 2035825,
        "device-id": 425035700,
        "direction": 1,
        "direction-text": "in",
        "door-id": 1,
        "event-id": 35,
        "event-reason": 2,
        "event-reason-text": "swipe open",
        "event-type": 1,
        "event-type-text": "card swipe",
        "timestamp": "2023-12-05 20:54:14 EST"
      }
    }
  },

I could identify the User by using the card-number, but it would be easier to identify by "User ID".

Thank you for your work!

**Comment by uhppoted** [comment]
re. running smoothly. Oh, **great** .. that's good news :-).

Unfortunately the controllers don't store any kind of custom user data with the card information (or if they do it's not accessible through the public API).

It would make a lot of things considerably simpler if it was possible, but there are some complex issues around maintaining something like user ID across multiple controllers so it probably made sense for the manufacturer not to support it.

For example, although it's fairly straightforward to just associate a card number with a person using a database, there are some hair-tearing out complications when it comes to keeping that association accurate for the events because there is generally no guarantee that the person using a card today is the same person that was using that same card a year ago.

**Comment by manu-benoit** [comment]
Thank you for your quick answer!
I'll do it with the card ID.

Regards!
