### ISSUE TITLE
strange mqtt issue

### ISSUE THREAD

**Issue by jfiger** [uhppoted/uhppoted-mqtt#21]
I use the  uhppoted-mqtt component on a Raspberry Pi to send mqtt messages to Home Assistant. Everything was working fine.
Suddenly, I stop receiving mqtt messages. After a reboot, I receive all old mqtt messages but no new messages. I need to reboot to get these messages.
Do you have any idea to solve this issue ?
My conf file is there [uhppoted.txt](https://github.com/user-attachments/files/15788186/uhppoted.txt)

**Comment by uhppoted** [comment]
Hi,

Weird! Your _conf_ file looks fine so it _may_ be a network issue:

1. When did the problem start ? (i.e. any idea what may have changed?)
2. By 'old messages' I'm assuming you mean events?
3. Which version of _uhppoted-mqtt_ are you running?
4. What is the model Raspberry Pi ?
5. Which MQTT broker are you using?
6. Are you running _uhppoted-mqtt_ as a daemon/service or in a Docker container?

**Comment by jfiger** [comment]
1.When did the problem start ? (i.e. any idea what may have changed?)
 **I am not sure, perhaps one or 2 months ago. Only security updates may have been deployed.**
2. By 'old messages' I'm assuming you mean events? **Yes**
3. Which version of uhppoted-mqtt are you running? **V0.8.4a**
4. What is the model Raspberry Pi ? **3B+**
5. Which MQTT broker are you using?  **Mosquito Home assistant**
6. Are you running uhppoted-mqtt as a daemon/service or in a Docker container? **daemon/service**

**Comment by uhppoted** [comment]
Hmm! Your _uhppoted.conf_ file has a `mqtt.topic.events.live = ./events/live` entry and according to my notes that was only available from _uhppoted-mqtt_ version v0.8.7. Would you mind double checking your version?
```
uhppoted-mqtt version
```

The reason events are not lost is because they are actually stored on the controller and on a restart _uhppoted-mqtt_ picks up where it left off. So if it stopped receiving events (for some as yet unknown reason) on restarting it would fetch any old, unreceived events in small'ish batches until it had caught up with the backlog. Which sounds more or less like what you are seeing?

The puzzle is why it stopped receiving events. It's possible that an idle connections is being 'put to sleep' by the operating system, although I've only seen that on _Docker_ and _MacOS_ - although I vaguely remember something about an somewhat controversial update to _systemd_ that may be related (will have to go dig it out).  

If you can dig out the logs over a restart/reboot they may shed some light on what is happening (look in `/var/uhppoted` or `/var/log`).

**However**, the whole event thing was reworked completely for v0.8.7, so it might be worth upgrading to the latest version if you can? See:
- [Rework events handling](https://github.com/uhppoted/uhppoted-mqtt/issues/16)
- [[bug?] old event published on each card swipe](https://github.com/uhppoted/uhppoted-mqtt/issues/15#issuecomment-1823295324)

**Please** backup your configuration and /var files before you do that though - and maybe also check the [README](https://github.com/uhppoted/uhppoted-mqtt#events).

**Comment by jfiger** [comment]
I have found the issue. Your first idea was correct. It's a network issue. I use a Zerotier virtual network to connect to the MQTT server. Using the direct LAN local address, UHPPOTE  is now working as expected  I made no change on the zerotier network  still working perfectly. I will investigate later this issue.
Thank you for your quick support.
BTW, I am very excited by your future Home Assistant add-on to get rid of the nefarious windows software provided by uhppote

**Comment by uhppoted** [comment]
Oh **great**!! Really glad you were able to resolve - thanks for letting me know!

re. nefarious. _ROTFL_. A couple of people are already using the _Home Assistant_ add-on so feel free to experiment with it if you want to - it's [apparently installable via HACS](https://github.com/uhppoted/uhppoted-app-home-assistant/discussions/4#discussioncomment-8934289). It's usable in it's current state and so far nobody has reported any serious issues - it's still just very, basic and there's a fair way to go before it's done..
